#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: "Titus12345@"
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#      database: postgres
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: iakwasititus@gmail.com
#    password: rqmufqslhbumbduv
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            connectiontimeout: 5000
#            timeout: 3000
#            writetimeout: 5000
#
#application:
#  security:
#    jwt:
#      secret-key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
#      expiration: 8640000
#  mailing:
#    frontend:
#      activation-url: http://localhost:5000/api/v1/auth/activate-account?token=
#
##server:
##  port: 8088
