spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "Titus12345@"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: postgres
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: iakwasititus@gmail.com
    password: rqmufqslhbumbduv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000

            #====================================

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: f93278da48867e8ad584
            client-secret: 8e9081c5098c732d588bca24f337af6cb5ca369f
          google:
            client-id: 792976069626-ifdrp523lrm9u22rvefndtrslmu29vqo.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "http://localhost:5000/api/v1/welcome"
            clientName: "Google"
            scope:
              - email
              - password

            #=====================================


application:
  security:
    jwt:
      secret-key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
      expiration: 86400000 # one day
  mailing:
    frontend:
      activation-url: http://localhost:5000/api/v1/auth/activate-account?token=

server:
  port: 5000

#  servlet:
#    context-path: /api/v1




